travis:
  secure:
    BINSTAR_TOKEN: cDVYCT5oHemIGjWct/T5BSxfkRlpYYOW9CnBmcvTna1V16KcpRcYFCAosKOHm4AoIM2AtUBIcZUddCgyCIk5iwDwWhg0xYCE+HqiHGUNmN0hHP+XUg6qpshq+ZW01MJK65Wsa2he+JX6mgnV8PNUaQSsVjBjETkn3RbhfidHXByj/V77vO5HPJY0vjeKKUCGt7FU8UFakoSsFUUJ2uYMFRyMCM//I+hwb5fMt8FJY2F+UOheFZWc3tKmUJyTP0XCHKXk5rct9KhcDfxMpoYe7dW/Rml8OXtCBIbudDXabhMaXGPGg+NQTxxeCYj369Em+1tBIyoONHI2qhvqMdBnV6OlIjM0lGyrManqKFOGUVQ+3fOffuqYH0+m7kCNBzPS1M2z5SoZ47GnAiaYETJnxTbo95D1ztGQoF0STgwHN3kqhwu21VUQlue8xzwAWd4ECr4vOhMSJiBrE4ysp77zENjbgaFF81l5A91HxF4BROzCwSOaZcypz10YtrcfwIvvk35qQazRBO70bAhveHPVFTWgC/HWnka1wqTgX+FrmPUCQL0UW64l5/EVqoZJRjzcJCcf68OWaAL1v0cYROalUSfIx46skhtCrAH24wH/mU1ppWoJp5VC3g2ONe5nHAk11ijuzuYzoHHKPc8ImOQ2HtzA4NiIWVtDfPmCrlA1dVE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
